import { ReactScan } from "@components/ReactScan";
import "@/app/globals.css";
import { type Metadata } from "next";
import { Header } from "@shared/Header";
import { Inter } from "next/font/google";
import { ConvexClientProvider } from "@providers/ConvexClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={`en`} className={`dark`}>
      <ReactScan />

      <body className={`${inter.className} antialiased`}>
        <ConvexClientProvider>
          <Header />

          <main className={`min-h-screen`}>{children}</main>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
